[package]
name = "setbot_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11" }
svg = { version = "0.10" }
rand = "0.8.5"
